version: '3'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8880:80
      - 80:80
    env_file:
      - ./wordpress.env
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  wpdb:
    image: mysql:5.7
    restart: always
    env_file:
      - ./wordpress.env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=stin
    volumes:
      - wordpress:/var/lib/mysql
  pg:
    image: postgres:11
    volumes:
      - stinvol:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
  web:
    build: './web'
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./web/project_root:/project_root
    ports:
      - "8000:8000"
      - "80:8000"
    depends_on:
      - pg

volumes:
  wordpress:
  stinvol:
    external: true
