version: '3'

services:
  odooweb:
    image: odoo:12.0
    depends_on:
      - db
    #ports:
      #- "8069:8069"
      #- "80:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  pg:
    image: postgres:11
    volumes:
      - stinvol:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
  web:
    build: './erm'
    volumes:
      - ./erm:/stinerm
    #ports:
      #- "80:5000"
    depends_on:
      - pg
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    env_file:
      - wordpress.env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file:
      - mysqldb.env
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  odoo-web-data:
  stinvol:
  wordpress:
  mysqldb:
