# Generated by Django 2.1.7 on 2019-05-02 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190502_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acad_position',
            field=models.CharField(blank=True, choices=[('na', 'ไม่มี'), ('ผู้ช่วยศาสตราจารย์', 'ผู้ช่วยศาสตราจารย์'), ('รองศาสตราจารย์', 'รองศาสตราจารย์'), ('ศาตราจารย์', 'ศาสตราจารย์')], max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_position',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='users.Department'),
        ),
    ]
