# Generated by Django 2.1.7 on 2019-05-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190502_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='acad_position',
            field=models.CharField(blank=True, choices=[('ผู้ช่วยศาสตราจารย์', 'ผู้ช่วยศาสตราจารย์'), ('รองศาสตราจารย์', 'รองศาสตราจารย์'), ('ศาตราจารย์', 'ศาสตราจารย์')], max_length=64),
        ),
    ]
