# Generated by Django 2.1.7 on 2019-05-02 02:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IRBRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irbcode', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'Not approved'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('exempted', 'Exempted')], default='exempted', max_length=32)),
                ('submitdate', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(max_length=250)),
                ('th_title', models.CharField(max_length=250)),
                ('intro', models.TextField(null=True)),
                ('objective', models.TextField(null=True)),
                ('method', models.TextField(null=True)),
                ('budget', models.FloatField(null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('th_abstract', models.TextField()),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ended', 'Ended'), ('began', 'Began'), ('holding', 'Holding'), ('terminated', 'Terminated')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='research.ProjectCategory')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='research.ProjectSubCategory'),
        ),
    ]
