# Generated by Django 2.1.7 on 2019-04-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ended', 'Ended'), ('began', 'Began'), ('holding', 'Holding'), ('terminated', 'Terminated')], default='draft', max_length=10),
        ),
    ]
