# Generated by Django 2.1.7 on 2019-04-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0003_auto_20190418_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRBRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irbcode', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'Not approved'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('exempted', 'Exempted')], default='exempted', max_length=32)),
                ('submitdate', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irb_records', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irb_records', to='research.Project')),
            ],
        ),
    ]
