"""added indexed and ranking fields

Revision ID: 0236db9e2ef9
Revises: b116682285db
Create Date: 2020-05-29 07:22:33.340704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0236db9e2ef9'
down_revision = 'b116682285db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_pub_records', sa.Column('indexed', sa.String(), nullable=True))
    op.add_column('project_pub_records', sa.Column('ranking', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_pub_records', 'ranking')
    op.drop_column('project_pub_records', 'indexed')
    # ### end Alembic commands ###
