"""add file url field

Revision ID: 05229c307d70
Revises: 327c8983628b
Create Date: 2022-10-18 23:32:57.215229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05229c307d70'
down_revision = '327c8983628b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'file_url')
    # ### end Alembic commands ###
