"""added a footer field

Revision ID: 05635c0bd3cf
Revises: 1cfa118ec6e8
Create Date: 2020-03-18 06:26:49.269041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05635c0bd3cf'
down_revision = '1cfa118ec6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_review_send_records', sa.Column('footer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_review_send_records', 'footer')
    # ### end Alembic commands ###
