"""added role field to the user model

Revision ID: 069f11c922d1
Revises: ec5ebdf07c3e
Create Date: 2020-02-27 22:58:44.601855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069f11c922d1'
down_revision = 'ec5ebdf07c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
