"""added user ID to the reviewer model

Revision ID: 0c04d8339926
Revises: 76a619074475
Create Date: 2020-03-13 11:29:23.743378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c04d8339926'
down_revision = '76a619074475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_reviewers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_reviewers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_reviewers', type_='foreignkey')
    op.drop_column('project_reviewers', 'user_id')
    # ### end Alembic commands ###
