"""changed the item field to nullable

Revision ID: 0c9eb3f66d03
Revises: d7028931879a
Create Date: 2022-08-18 03:33:49.473032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9eb3f66d03'
down_revision = 'd7028931879a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('researcher_development_expense_items', 'item',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('researcher_development_expense_items', 'item',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
