"""added education model

Revision ID: 0da350474d0c
Revises: 2f121ea06309
Create Date: 2020-02-13 01:39:17.547248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da350474d0c'
down_revision = '2f121ea06309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('degree_title', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('educations')
    # ### end Alembic commands ###
