"""added contribution field

Revision ID: 128019e2b94f
Revises: 1d61272e2032
Create Date: 2022-03-23 08:14:28.705287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128019e2b94f'
down_revision = '1d61272e2032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('contribution', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'contribution')
    # ### end Alembic commands ###
