"""added edited at field

Revision ID: 1625bfe8180d
Revises: 6f6a0f3ade5e
Create Date: 2020-05-11 02:31:56.975794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1625bfe8180d'
down_revision = '6f6a0f3ade5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_language_editing_supports', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_language_editing_supports', 'edited_at')
    # ### end Alembic commands ###
