"""added desc field to the budget subcategory model

Revision ID: 1d61272e2032
Revises: fcbd44061c2e
Create Date: 2021-02-03 16:01:05.220206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d61272e2032'
down_revision = 'fcbd44061c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_budget_sub_category', sa.Column('desc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_budget_sub_category', 'desc')
    # ### end Alembic commands ###
