"""added completion field

Revision ID: 1e48e62394ac
Revises: daa0aedfc683
Create Date: 2020-05-11 22:10:19.268686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e48e62394ac'
down_revision = 'daa0aedfc683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_gantt_activity', sa.Column('completion', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_gantt_activity', 'completion')
    # ### end Alembic commands ###
