"""added to field to store email of the recipient

Revision ID: 1f1e8079b335
Revises: 064c47765ae5
Create Date: 2020-03-18 06:47:24.423306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1e8079b335'
down_revision = '064c47765ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_review_send_records', sa.Column('to', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_review_send_records', 'to')
    # ### end Alembic commands ###
