"""removed item ID field

Revision ID: 25e3a6ec565e
Revises: 70fcadfeac0d
Create Date: 2020-05-12 00:17:57.636854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e3a6ec565e'
down_revision = '70fcadfeac0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_budget_item', 'item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_budget_item', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
