"""added prospected journals field

Revision ID: 2cdd03795f97
Revises: 995effb19e38
Create Date: 2020-03-08 21:20:02.000649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdd03795f97'
down_revision = '995effb19e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_archives', sa.Column('prospected_journals', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('prospected_journals', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'prospected_journals')
    op.drop_column('project_archives', 'prospected_journals')
    # ### end Alembic commands ###
