"""added a released date field to the review record

Revision ID: 2ec371bd20c2
Revises: fcde7cc52eb7
Create Date: 2020-08-28 10:07:25.863860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec371bd20c2'
down_revision = 'fcde7cc52eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_review_records', sa.Column('released_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_review_records', 'released_at')
    # ### end Alembic commands ###
