"""added funding status field

Revision ID: 327c8983628b
Revises: 252c5f80b982
Create Date: 2022-10-18 23:13:58.856089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '327c8983628b'
down_revision = '252c5f80b982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_milestone', sa.Column('funding_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_milestone', 'funding_status')
    # ### end Alembic commands ###
