"""added received datetime field to the milestone model

Revision ID: 456208d477bb
Revises: 99582b869c47
Create Date: 2022-03-23 16:17:05.518656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456208d477bb'
down_revision = '99582b869c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_milestone', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_milestone', 'received_at')
    # ### end Alembic commands ###
