"""added final report url field

Revision ID: 45637236103b
Revises: 7f35137a85a6
Create Date: 2020-09-28 20:46:31.635317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45637236103b'
down_revision = '7f35137a85a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('final_report_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'final_report_url')
    # ### end Alembic commands ###
