"""added use or applications field

Revision ID: 47cee193a66f
Revises: 2cdd03795f97
Create Date: 2020-03-08 23:46:01.996603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cee193a66f'
down_revision = '2cdd03795f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_archives', sa.Column('use_applications', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('use_applications', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'use_applications')
    op.drop_column('project_archives', 'use_applications')
    # ### end Alembic commands ###
