"""added publication author model

Revision ID: 498ee2fb2596
Revises: fa0fb9fd29e3
Create Date: 2020-04-17 00:42:56.670885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498ee2fb2596'
down_revision = 'fa0fb9fd29e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_publication_authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pub_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pub_id'], ['project_pub_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_publication_authors')
    # ### end Alembic commands ###
