"""added file upload fields to the budget item model

Revision ID: 49fe5417fc7c
Revises: 9680d34fda15
Create Date: 2022-04-11 09:57:07.406592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fe5417fc7c'
down_revision = '9680d34fda15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_budget_item_docs')
    op.add_column('project_budget_item', sa.Column('file_detail', sa.Text(), nullable=True))
    op.add_column('project_budget_item', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('project_budget_item', sa.Column('file_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_budget_item', 'file_url')
    op.drop_column('project_budget_item', 'file_name')
    op.drop_column('project_budget_item', 'file_detail')
    op.create_table('project_budget_item_docs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('budget_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['budget_item_id'], ['project_budget_item.id'], name='project_budget_item_docs_budget_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_budget_item_docs_pkey')
    )
    # ### end Alembic commands ###
