"""added detail field to the budget item

Revision ID: 4b21899d15b1
Revises: a987cbd84c4d
Create Date: 2022-03-23 12:15:20.082788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b21899d15b1'
down_revision = 'a987cbd84c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_budget_item', sa.Column('detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_budget_item', 'detail')
    # ### end Alembic commands ###
