"""added approved and approve datetime field

Revision ID: 5da54be04d26
Revises: 05229c307d70
Create Date: 2022-10-19 00:06:43.954728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5da54be04d26'
down_revision = '05229c307d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_milestone', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('project_milestone', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_milestone', 'approved_at')
    op.drop_column('project_milestone', 'approved')
    # ### end Alembic commands ###
