"""added a foreign key to the figure model

Revision ID: 61652ad490c0
Revises: 8f2b68d1bc6a
Create Date: 2020-03-08 23:56:28.713763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61652ad490c0'
down_revision = '8f2b68d1bc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_figures', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_figures', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_figures', type_='foreignkey')
    op.drop_column('project_figures', 'project_id')
    # ### end Alembic commands ###
