"""added development types and categories models

Revision ID: 649c55084d2c
Revises: f86295a3a057
Create Date: 2022-08-17 23:59:31.148884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649c55084d2c'
down_revision = 'f86295a3a057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher_development_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('researcher_development_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('researcher_development_types')
    op.drop_table('researcher_development_categories')
    # ### end Alembic commands ###
