"""added other docs field

Revision ID: 6f6a0f3ade5e
Revises: 4bc13450b936
Create Date: 2020-05-11 01:28:55.465274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6a0f3ade5e'
down_revision = '4bc13450b936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_language_editing_supports', sa.Column('other_docs', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_language_editing_supports', 'other_docs')
    # ### end Alembic commands ###
