"""replaced category with subcategory for the itmem model

Revision ID: 70fcadfeac0d
Revises: d9589aefe021
Create Date: 2020-05-12 00:12:48.540329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fcadfeac0d'
down_revision = 'd9589aefe021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_budget_sub_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['project_budget_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project_budget_item', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.drop_constraint('project_budget_item_category_id_fkey', 'project_budget_item', type_='foreignkey')
    op.create_foreign_key(None, 'project_budget_item', 'project_budget_sub_category', ['sub_category_id'], ['id'])
    op.drop_column('project_budget_item', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_budget_item', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_budget_item', type_='foreignkey')
    op.create_foreign_key('project_budget_item_category_id_fkey', 'project_budget_item', 'project_budget_category', ['category_id'], ['id'])
    op.drop_column('project_budget_item', 'sub_category_id')
    op.drop_table('project_budget_sub_category')
    # ### end Alembic commands ###
