"""added reviewer and reviewer group models with the associated table

Revision ID: 76a619074475
Revises: a8566dc73835
Create Date: 2020-03-13 11:26:19.914272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a619074475'
down_revision = 'a8566dc73835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_reviewer_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_reviewers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_title', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewer_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['project_reviewer_groups.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['project_reviewers.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'reviewer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewer_groups')
    op.drop_table('project_reviewers')
    op.drop_table('project_reviewer_groups')
    # ### end Alembic commands ###
