"""added title comment to the review record model

Revision ID: 7f35137a85a6
Revises: 2ec371bd20c2
Create Date: 2020-09-28 20:15:45.922279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f35137a85a6'
down_revision = '2ec371bd20c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_review_records', sa.Column('title_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_review_records', 'title_comment')
    # ### end Alembic commands ###
