"""added a form model for the international conference support

Revision ID: 846ffac1f3ab
Revises: c65fc1adb664
Create Date: 2020-06-12 02:57:26.579505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846ffac1f3ab'
down_revision = 'c65fc1adb664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher_intl_conference_supports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('article_title', sa.String(), nullable=True),
    sa.Column('organizer', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('conference_date', sa.Date(), nullable=True),
    sa.Column('presentation_date', sa.Date(), nullable=True),
    sa.Column('presentation_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('researcher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('researcher_intl_conference_supports')
    # ### end Alembic commands ###
