"""added a field for user activation

Revision ID: 8646cb859a42
Revises: b18eb0097cba
Create Date: 2020-06-16 14:47:02.464552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8646cb859a42'
down_revision = 'b18eb0097cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_activated')
    # ### end Alembic commands ###
