"""added project summary record model

Revision ID: 8b076f40d500
Revises: dd0d98fec946
Create Date: 2020-05-12 17:52:34.596666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b076f40d500'
down_revision = 'dd0d98fec946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activity', sa.Unicode(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['project_milestone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_summary')
    # ### end Alembic commands ###
