"""updated the ethical review record model according to the official form

Revision ID: 8d7fab21c60b
Revises: 46f027b50c87
Create Date: 2020-03-30 13:07:11.560278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7fab21c60b'
down_revision = '46f027b50c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_ethic_review_records', sa.Column('consent_revision', sa.Text(), nullable=True))
    op.add_column('project_ethic_review_records', sa.Column('doc_revision', sa.Text(), nullable=True))
    op.add_column('project_ethic_review_records', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('project_ethic_review_records', sa.Column('project_revision', sa.Text(), nullable=True))
    op.add_column('project_ethic_review_records', sa.Column('tool_revision', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_ethic_review_records', 'tool_revision')
    op.drop_column('project_ethic_review_records', 'project_revision')
    op.drop_column('project_ethic_review_records', 'note')
    op.drop_column('project_ethic_review_records', 'doc_revision')
    op.drop_column('project_ethic_review_records', 'consent_revision')
    # ### end Alembic commands ###
