"""fixed error on title and reserch tool field

Revision ID: 906ab2a93d4a
Revises: e232deb78f38
Create Date: 2020-03-30 12:44:12.527701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906ab2a93d4a'
down_revision = 'e232deb78f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('research_tool', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'research_tool')
    # ### end Alembic commands ###
