"""added file url field to milestone model

Revision ID: 99582b869c47
Revises: 4b21899d15b1
Create Date: 2022-03-23 15:08:18.769895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99582b869c47'
down_revision = '4b21899d15b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_milestone', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_milestone', 'file_url')
    # ### end Alembic commands ###
