"""added a bunch of fields to the project record form

Revision ID: a036de5d62e9
Revises: 45637236103b
Create Date: 2020-09-29 11:56:23.184709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a036de5d62e9'
down_revision = '45637236103b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('conceptual_framework', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('glossary', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('keywords', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('literature_review', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('references', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('research_cluster', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('research_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('scope', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'scope')
    op.drop_column('projects', 'research_type')
    op.drop_column('projects', 'research_cluster')
    op.drop_column('projects', 'references')
    op.drop_column('projects', 'literature_review')
    op.drop_column('projects', 'keywords')
    op.drop_column('projects', 'glossary')
    op.drop_column('projects', 'conceptual_framework')
    # ### end Alembic commands ###
