"""added JSON field for members, milestones and figures

Revision ID: a8566dc73835
Revises: b29074df57ae
Create Date: 2020-03-13 10:28:28.790227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8566dc73835'
down_revision = 'b29074df57ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_archives', sa.Column('figures', sa.JSON(), nullable=True))
    op.add_column('project_archives', sa.Column('members', sa.JSON(), nullable=True))
    op.add_column('project_archives', sa.Column('milestones', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_archives', 'milestones')
    op.drop_column('project_archives', 'members')
    op.drop_column('project_archives', 'figures')
    # ### end Alembic commands ###
