"""added category field for the budget item

Revision ID: a987cbd84c4d
Revises: 128019e2b94f
Create Date: 2022-03-23 12:06:43.996955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a987cbd84c4d'
down_revision = '128019e2b94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_budget_item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_budget_item', 'project_budget_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_budget_item', type_='foreignkey')
    op.drop_column('project_budget_item', 'category_id')
    # ### end Alembic commands ###
