"""added published reward model

Revision ID: ae694ea0163c
Revises: 1625bfe8180d
Create Date: 2020-05-11 05:49:45.199922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae694ea0163c'
down_revision = '1625bfe8180d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_pub_rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pub_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('apc', sa.Unicode(), nullable=True),
    sa.Column('reward', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['pub_id'], ['project_pub_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_pub_rewards')
    # ### end Alembic commands ###
