"""added status field to reward model

Revision ID: aea9e3a08549
Revises: ae694ea0163c
Create Date: 2020-05-11 14:21:39.681602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea9e3a08549'
down_revision = 'ae694ea0163c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_pub_rewards', sa.Column('status', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_pub_rewards', 'status')
    # ### end Alembic commands ###
