"""added some more fields

Revision ID: b18eb0097cba
Revises: 846ffac1f3ab
Create Date: 2020-06-12 03:00:05.314842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18eb0097cba'
down_revision = '846ffac1f3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researcher_intl_conference_supports', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('researcher_intl_conference_supports', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('researcher_intl_conference_supports', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researcher_intl_conference_supports', 'submitted_at')
    op.drop_column('researcher_intl_conference_supports', 'edited_at')
    op.drop_column('researcher_intl_conference_supports', 'approved_at')
    # ### end Alembic commands ###
