"""added a deadline field

Revision ID: b29074df57ae
Revises: edc29d3b556f
Create Date: 2020-03-09 08:09:11.948097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29074df57ae'
down_revision = 'edc29d3b556f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_milestone', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_milestone', 'deadline')
    # ### end Alembic commands ###
