"""added a relationship between project and the funding source models

Revision ID: b5eccd86d4e3
Revises: c8e9b62f8fcb
Create Date: 2020-05-29 14:06:16.886700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5eccd86d4e3'
down_revision = 'c8e9b62f8fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_fund_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('from', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('fund_source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'project_fund_sources', ['fund_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'fund_source_id')
    op.drop_table('project_fund_sources')
    # ### end Alembic commands ###
