"""added fields for bookbank and finance summary file upload

Revision ID: c2772720e5b1
Revises: ffc49908a48b
Create Date: 2020-10-01 19:59:12.651026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2772720e5b1'
down_revision = 'ffc49908a48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('bookbank_cover_file_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('bookbank_last_page_file_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('finance_summary_file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'finance_summary_file_url')
    op.drop_column('projects', 'bookbank_last_page_file_url')
    op.drop_column('projects', 'bookbank_cover_file_url')
    # ### end Alembic commands ###
