"""added contract file upload url field

Revision ID: c65fc1adb664
Revises: 14646633861b
Create Date: 2020-06-12 02:38:56.399423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65fc1adb664'
down_revision = '14646633861b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_proposal_development_supports', sa.Column('contract_file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_proposal_development_supports', 'contract_file_url')
    # ### end Alembic commands ###
