"""added dirty field to Gantt activity field

Revision ID: cf6fdcfc0902
Revises: 1e48e62394ac
Create Date: 2020-05-11 22:42:54.748173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6fdcfc0902'
down_revision = '1e48e62394ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_gantt_activity', sa.Column('dirty', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_gantt_activity', 'dirty')
    # ### end Alembic commands ###
