"""added mail info model

Revision ID: d3ab7f18470c
Revises: 8646cb859a42
Create Date: 2020-07-31 10:32:55.514406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ab7f18470c'
down_revision = '8646cb859a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_info')
    # ### end Alembic commands ###
