"""added category_id field to budget category and item model

Revision ID: d9589aefe021
Revises: 9d0273fe5b92
Create Date: 2020-05-12 00:09:03.970536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9589aefe021'
down_revision = '9d0273fe5b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_budget_category', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('project_budget_item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_budget_item', 'project_budget_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_budget_item', type_='foreignkey')
    op.drop_column('project_budget_item', 'category_id')
    op.drop_column('project_budget_category', 'category_id')
    # ### end Alembic commands ###
