"""added the Gantt activity model

Revision ID: daa0aedfc683
Revises: aea9e3a08549
Create Date: 2020-05-11 20:41:51.812140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'daa0aedfc683'
down_revision = 'aea9e3a08549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_gantt_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['project_milestone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('project_milestone', 'deadline')
    op.drop_column('project_milestone', 'goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_milestone', sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('project_milestone', sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_table('project_gantt_activity')
    # ### end Alembic commands ###
