"""added file url field for a file attachment

Revision ID: db979b4a69f7
Revises: dc6a15385526
Create Date: 2022-04-28 12:56:04.398328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db979b4a69f7'
down_revision = 'dc6a15385526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_review_records', sa.Column('file_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_review_records', 'file_url')
    # ### end Alembic commands ###
