"""added  submit datetime field to milestone model

Revision ID: dc6a15385526
Revises: 49fe5417fc7c
Create Date: 2022-04-11 13:10:08.563704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6a15385526'
down_revision = '49fe5417fc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_milestone', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_milestone', 'submitted_at')
    # ### end Alembic commands ###
