"""added milestone ID to the budget item model

Revision ID: dd0d98fec946
Revises: 25e3a6ec565e
Create Date: 2020-05-12 13:33:45.161406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0d98fec946'
down_revision = '25e3a6ec565e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_budget_item', sa.Column('milestone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_budget_item', 'project_milestone', ['milestone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_budget_item', type_='foreignkey')
    op.drop_column('project_budget_item', 'milestone_id')
    # ### end Alembic commands ###
