"""added expected benefit field to the project record model

Revision ID: e156fd2a9a46
Revises: e438f348f63e
Create Date: 2020-09-30 11:10:58.479031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e156fd2a9a46'
down_revision = 'e438f348f63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('expected_benefit', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'expected_benefit')
    # ### end Alembic commands ###
