"""updated the application model according to the official form

Revision ID: e232deb78f38
Revises: a7d996712854
Create Date: 2020-03-30 12:38:41.731246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e232deb78f38'
down_revision = 'a7d996712854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('commercial_how', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('commercial_outcome', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('finished_year', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('indirect_how', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('indirect_outcome', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('policy_how', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('policy_outcome', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('public_how', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('public_outcome', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('applications', 'detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('applications', 'title')
    op.drop_column('applications', 'public_outcome')
    op.drop_column('applications', 'public_how')
    op.drop_column('applications', 'policy_outcome')
    op.drop_column('applications', 'policy_how')
    op.drop_column('applications', 'indirect_outcome')
    op.drop_column('applications', 'indirect_how')
    op.drop_column('applications', 'finished_year')
    op.drop_column('applications', 'commercial_outcome')
    op.drop_column('applications', 'commercial_how')
    # ### end Alembic commands ###
