"""added a rejected at field

Revision ID: e2a0b40c6aca
Revises: 58c75f7f1601
Create Date: 2022-08-18 01:31:26.665256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a0b40c6aca'
down_revision = '58c75f7f1601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researcher_development_records', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researcher_development_records', 'rejected_at')
    # ### end Alembic commands ###
