"""added more fields to the publication model

Revision ID: e4c006b117b0
Revises: 9f862dc9dea2
Create Date: 2020-03-30 13:44:26.408823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c006b117b0'
down_revision = '9f862dc9dea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_pub_records', sa.Column('category', sa.String(), nullable=True))
    op.add_column('project_pub_records', sa.Column('issue_no', sa.String(), nullable=True))
    op.add_column('project_pub_records', sa.Column('month', sa.String(), nullable=True))
    op.add_column('project_pub_records', sa.Column('page_no', sa.String(), nullable=True))
    op.add_column('project_pub_records', sa.Column('title', sa.String(), nullable=False))
    op.add_column('project_pub_records', sa.Column('volume', sa.String(), nullable=True))
    op.add_column('project_pub_records', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_pub_records', 'year')
    op.drop_column('project_pub_records', 'volume')
    op.drop_column('project_pub_records', 'title')
    op.drop_column('project_pub_records', 'page_no')
    op.drop_column('project_pub_records', 'month')
    op.drop_column('project_pub_records', 'issue_no')
    op.drop_column('project_pub_records', 'category')
    # ### end Alembic commands ###
