"""added some more fields to the milestone model

Revision ID: e82d1bbfa176
Revises: cf6fdcfc0902
Create Date: 2020-05-11 23:39:46.575924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82d1bbfa176'
down_revision = 'cf6fdcfc0902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_milestone', sa.Column('obstacle', sa.Text(), nullable=True))
    op.add_column('project_milestone', sa.Column('opinion', sa.Text(), nullable=True))
    op.add_column('project_milestone', sa.Column('plan', sa.Text(), nullable=True))
    op.add_column('project_milestone', sa.Column('related_activity', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_milestone', 'related_activity')
    op.drop_column('project_milestone', 'plan')
    op.drop_column('project_milestone', 'opinion')
    op.drop_column('project_milestone', 'obstacle')
    # ### end Alembic commands ###
