"""added a creator ID field to the project record

Revision ID: ec5ebdf07c3e
Revises: 504e91e19728
Create Date: 2020-02-27 22:04:50.026337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5ebdf07c3e'
down_revision = '504e91e19728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'creator_id')
    # ### end Alembic commands ###
