"""added dates to the project record model

Revision ID: f384c81e6b0f
Revises: 0ddc3d8183f2
Create Date: 2020-02-13 02:45:58.029323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f384c81e6b0f'
down_revision = '0ddc3d8183f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('denied_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'submitted_at')
    op.drop_column('projects', 'denied_at')
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'approved_at')
    # ### end Alembic commands ###
