"""added fields for close request and close datetime

Revision ID: f86295a3a057
Revises: db979b4a69f7
Create Date: 2022-04-29 05:57:31.363709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86295a3a057'
down_revision = 'db979b4a69f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('close_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'closed_at')
    op.drop_column('projects', 'close_requested_at')
    # ### end Alembic commands ###
