"""removed project FK and added the ethic FK instead in the ethic review model

Revision ID: fa0614c1afe4
Revises: d16e5f825ca0
Create Date: 2020-06-04 03:23:18.671660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0614c1afe4'
down_revision = 'd16e5f825ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_ethic_review_records', sa.Column('ethic_id', sa.Integer(), nullable=True))
    op.drop_constraint('project_ethic_review_records_project_id_fkey', 'project_ethic_review_records', type_='foreignkey')
    op.create_foreign_key(None, 'project_ethic_review_records', 'project_ethics', ['ethic_id'], ['id'])
    op.drop_column('project_ethic_review_records', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_ethic_review_records', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_ethic_review_records', type_='foreignkey')
    op.create_foreign_key('project_ethic_review_records_project_id_fkey', 'project_ethic_review_records', 'projects', ['project_id'], ['id'])
    op.drop_column('project_ethic_review_records', 'ethic_id')
    # ### end Alembic commands ###
