"""added url and doi fields to the pub model

Revision ID: fa0fb9fd29e3
Revises: e4c006b117b0
Create Date: 2020-04-16 23:56:52.380098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0fb9fd29e3'
down_revision = 'e4c006b117b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_pub_records', sa.Column('DOI', sa.String(), nullable=True))
    op.add_column('project_pub_records', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_pub_records', 'url')
    op.drop_column('project_pub_records', 'DOI')
    # ### end Alembic commands ###
