"""added email field to the external team member

Revision ID: fcbd44061c2e
Revises: 7cd09b830b79
Create Date: 2020-11-16 16:26:09.678009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcbd44061c2e'
down_revision = '7cd09b830b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'email')
    # ### end Alembic commands ###
