"""added summarized field to the review record model

Revision ID: fcde7cc52eb7
Revises: d3ab7f18470c
Create Date: 2020-08-28 09:19:39.116558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcde7cc52eb7'
down_revision = 'd3ab7f18470c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_review_records', sa.Column('summarized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_review_records', 'summarized')
    # ### end Alembic commands ###
